receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "https://xray.${env:AWS_REGION}.amazonaws.com/"
    auth:
      authenticator: sigv4auth

extensions:
  sigv4auth:

service:
  extensions: [sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [debug]
  telemetry:
    metrics:
      address: localhost:8888
